# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gowebly < Formula
  desc "A next-generation CLI tool that makes it easy to create amazing web applications with Go on the backend, using htmx, hyperscript or Alpine.js and the most popular CSS frameworks on the frontend.
"
  homepage "https://github.com/gowebly/gowebly"
  version "2.4.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gowebly/gowebly/releases/download/v2.4.0/gowebly_2.4.0_darwin_amd64.tar.gz"
      sha256 "9effb1e67fdc23b5eb09c83e9c24891767dc37ddbafca91d8b6bb25954750bf6"

      def install
        bin.install "gowebly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gowebly/gowebly/releases/download/v2.4.0/gowebly_2.4.0_darwin_arm64.tar.gz"
      sha256 "e3dca2e020a5a9e358af0ce7fd285372f55a02c751e9a8b7d217ffbab1e1987d"

      def install
        bin.install "gowebly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gowebly/gowebly/releases/download/v2.4.0/gowebly_2.4.0_linux_amd64.tar.gz"
      sha256 "6d8e6f67799f013ae0fd671df68d3805414deaea31426b143512ba69db7c4463"

      def install
        bin.install "gowebly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gowebly/gowebly/releases/download/v2.4.0/gowebly_2.4.0_linux_arm64.tar.gz"
      sha256 "8ff241211d94e439fd5e64517f2b55d6ae7de02d51b5b2cc90bd6f9b1f87fd97"

      def install
        bin.install "gowebly"
      end
    end
  end

  def caveats
    <<~EOS
      After install the Gowebly CLI, create a new project:

      $ gowebly create

      💡 Note: See the Complete user guide (https://gowebly.org/) to get a general information.
    EOS
  end
end
