# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gowebly < Formula
  desc "A next-generation CLI tool that makes it easy to create amazing web applications with Go on the backend, using htmx, hyperscript or Alpine.js and the most popular CSS frameworks on the frontend.
"
  homepage "https://github.com/gowebly/gowebly"
  version "3.0.0"
  license "Apache 2.0"

  on_macos do
    on_intel do
      url "https://github.com/gowebly/gowebly/releases/download/v3.0.0/gowebly_3.0.0_darwin_amd64.tar.gz"
      sha256 "6863f7d8ec71996cf57235e2a3d89c96674c009ddcdc8ab0c445b43fc41af4dd"

      def install
        bin.install "gowebly"
      end
    end
    on_arm do
      url "https://github.com/gowebly/gowebly/releases/download/v3.0.0/gowebly_3.0.0_darwin_arm64.tar.gz"
      sha256 "30f9f60c3ec35b25c254cc1669793555ec7ac66dd60d390d0ca32edb85767f21"

      def install
        bin.install "gowebly"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gowebly/gowebly/releases/download/v3.0.0/gowebly_3.0.0_linux_amd64.tar.gz"
        sha256 "ad63cc6181fa621c84dc4b1fc439af17a36d535c7a0835c8911d494b18e7960a"

        def install
          bin.install "gowebly"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gowebly/gowebly/releases/download/v3.0.0/gowebly_3.0.0_linux_arm64.tar.gz"
        sha256 "cd0884e1334c83fbcf241c60d612365726c66249cbe9e3092bc83ac4bea6a5bc"

        def install
          bin.install "gowebly"
        end
      end
    end
  end

  def caveats
    <<~EOS
      After install the Gowebly CLI, create a new project:

      $ gowebly create

      💡 See the Complete user guide (https://gowebly.org/) to get a general information.
      ✨ Also, you can support the author on Boosty: https://boosty.to/koddr
    EOS
  end
end
